/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.equivalencia.telas;

/**
 *
 * @author esantos
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        btnArea = new javax.swing.JButton();
        btnCurso = new javax.swing.JButton();
        btnGrupoEquiv = new javax.swing.JButton();
        btnEquivalencia = new javax.swing.JButton();
        btnPpc = new javax.swing.JButton();
        btnUnidades = new javax.swing.JButton();
        menPricipal = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadArea = new javax.swing.JMenuItem();
        menCadCurso = new javax.swing.JMenuItem();
        menCadPpc = new javax.swing.JMenuItem();
        menCadGrupo = new javax.swing.JMenuItem();
        menCadUnidade = new javax.swing.JMenuItem();
        menCadUsuario = new javax.swing.JMenuItem();
        menEquiv = new javax.swing.JMenu();
        menEquivalencia = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menLogout = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();
        menAjuda = new javax.swing.JMenu();
        menFluxo = new javax.swing.JMenuItem();
        menManual = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIS Equivalência - SENAI Vitória - Tela Principal");
        setPreferredSize(new java.awt.Dimension(1366, 768));

        btnArea.setText("Área Tecnológica");

        btnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/area.png"))); // NOI18N

        menCad.setText("Cadastro");
        menCad.setEnabled(false);

        menCadArea.setText("Áreas Tecnologica");
        menCadArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadAreaActionPerformed(evt);
            }
        });
        menCad.add(menCadArea);

        menCadCurso.setText("Cursos");
        menCad.add(menCadCurso);

        menCadPpc.setText("PPC");
        menCad.add(menCadPpc);

        menCadGrupo.setText("Grupos de Equivalência ");
        menCad.add(menCadGrupo);

        menCadUnidade.setText("Unidades Curriculares");
        menCad.add(menCadUnidade);

        menCadUsuario.setText("Usuários");
        menCad.add(menCadUsuario);

        menPricipal.add(menCad);

        menEquiv.setText("Equivalencia");

        menEquivalencia.setText("Realizar");
        menEquiv.add(menEquivalencia);

        menPricipal.add(menEquiv);

        menOpc.setText("Opções");

        menLogout.setText("Logout");
        menLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLogoutActionPerformed(evt);
            }
        });
        menOpc.add(menLogout);

        menSair.setText("Sair");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        menOpc.add(menSair);

        menPricipal.add(menOpc);

        menAjuda.setText("Ajuda");

        menFluxo.setText("Fluxo de processo");
        menAjuda.add(menFluxo);

        menManual.setText("Manual");
        menAjuda.add(menManual);

        menPricipal.add(menAjuda);

        setJMenuBar(menPricipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPpc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrupoEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(503, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrupoEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPpc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(376, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCadAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadAreaActionPerformed

    private void menLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLogoutActionPerformed
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menLogoutActionPerformed

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnCurso;
    private javax.swing.JButton btnEquivalencia;
    private javax.swing.JButton btnGrupoEquiv;
    private javax.swing.JButton btnPpc;
    private javax.swing.JButton btnUnidades;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menAjuda;
    public static javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadArea;
    private javax.swing.JMenuItem menCadCurso;
    private javax.swing.JMenuItem menCadGrupo;
    private javax.swing.JMenuItem menCadPpc;
    private javax.swing.JMenuItem menCadUnidade;
    private javax.swing.JMenuItem menCadUsuario;
    private javax.swing.JMenu menEquiv;
    private javax.swing.JMenuItem menEquivalencia;
    private javax.swing.JMenuItem menFluxo;
    private javax.swing.JMenuItem menLogout;
    private javax.swing.JMenuItem menManual;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenuBar menPricipal;
    private javax.swing.JMenuItem menSair;
    // End of variables declaration//GEN-END:variables
}
